### ISSUE TITLE
Problem with credentials

### ISSUE THREAD

**Issue by dokato** [nfultz/AWR.Athena#13]
Hi, thanks a lot for the package!
I've tried to play around it recenlty, but I keep getting error:
```
con <- dbConnect(AWR.Athena::Athena(), region='eu-west-2',
                 s3_staging_dir='s3://aws-athena-query-results-XXXXX',
                 schema_name='default')

Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  : 
  com.amazonaws.athena.jdbc.shaded.com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain
```
Even though I tried to set my credentials in many different ways. In `~/.aws/credentials` I've got:
```
AWS_ACCESS_KEY_ID="accessaccess"
AWS_SECRET_ACCESS_KEY="secretsecret"
```
Similarly in R:
```
Sys.setenv("AWS_ACCESS_KEY_ID" = "accessaccess",
           "AWS_SECRET_ACCESS_KEY" = "secretsecret")
```

None of above worked for me. Any guesses what could go wrong?

**Comment by hrbrmstr** [comment]
Do you have the same issue if you try them with https://github.com/cloudyr/roto.athena and the ODBC interface to Athena? If so it may be a local system config problem vs an rjava/awr.athena problem.

**Comment by nfultz** [comment]
It seems like you are doing it right; this  package uses the default provider chaing - https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default

You might also try `~/.aws/config`

Can you check if  AWS_PROFILE or AWS_CREDENTIAL_PROFILES_FILE is set to something and shortcutting around the other defaults? 

Also are you running locally or on EC2?

**Comment by daroczig** [comment]
> Even though I tried to set my credentials in many different ways. In ~/.aws/credentials I've got:

Do you also have the `[default]` section header above the key id/secret?

> Similarly in R: ... `Sys.setenv`

Did you run that before loading `AWR.Athena`?

**Comment by dokato** [comment]
Thank guys for a quick reply. I was trying to run it locally and looks like @daroczig was right. I restarted R session, loaded env vars first and then AWR.Athena and it went smooth this time.

Thanks, @nfultz for a great package!
