### ISSUE TITLE
Provide for AWR::Athena() a path variable to AthenaJDBC41_2.0.7.jar

### ISSUE THREAD

**Issue by Zirkonium88** [nfultz/AWR.Athena#23]
## Description

Thanks for this great tool. I have the problem, that I can't figure out where to put the AthenaJDBC41_2.0.7.jar to avoid downloading it on Docker run.

## Rationale

I would like to use my Docker Container on AWS Fargate. AWS Fargate is natively stateless Docker service. So, I would like to provide the AthenaJDBC41_2.0.7.jar by default within the Docker Container to increase the spin up time of my Docker Container. Therefore, it would be nice to have a path variable within `AWR::Athena()` which points to the file. 

## Use case

I need a high scalable BI app. Until now it takes up to 5 seconds to download the AthenaJDBC41_2.0.7.jar within my Container, which is definitely a long time. If the up app gets terminated, this happen every time.

**Comment by daroczig** [comment]
Hm, not sure what might be the problem, but if you install `AWR.Athena` in the Docker image, the `jar` will be downloaded in that process. So simply using the Docker image should NOT download the `jar` file. To rephrase: downloading the `jar` file happens at `install.packages` time and not when you `library(AWR.Athena)`.

Is the package installed in your `Dockerfile` / Docker image?

**Comment by Zirkonium88** [comment]
So far, I used `RUN R -e "install.packages('AWR.Athena', repos='http://cran.rstudio.com/')` within my `Dockerfile`. I will give a try on `RUN R -e "devtools::install_github('nfultz/AWR.Athena')"`. I'm using `FROM rocker/shiny-verse:3.5 ` as base Docker image.

**Comment by daroczig** [comment]
No need to switch away from `install.packages`, there must be some other issue.

This is what you should see in your Docker build:

```
> install.packages('AWR.Athena')
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/AWR.Athena_2.0.7-0.tar.gz'
Content type 'application/x-gzip' length 4019 bytes
==================================================
downloaded 4019 bytes

* installing *source* package ‘AWR.Athena’ ...
** package ‘AWR.Athena’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
trying URL 'https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.7/AthenaJDBC41_2.0.7.jar'
Content type 'binary/octet-stream' length 8120029 bytes (7.7 MB)
==================================================
downloaded 7.7 MB

** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (AWR.Athena)

The downloaded source packages are in
	‘/tmp/Rtmp4au4Yf/downloaded_packages’
```

So the jar file downloaded at installation time.

Can you please share the related parts of your Docker build logs + related logs on the `jar` being downloaded after a `library(AWR.Athena)` later on?

**Comment by Zirkonium88** [comment]
Thanks again for the quick response! Using `install.packages('AWR.Athena')`, I got the same output you stated and the following output on wget on my localhost: 

```
Loading required package: DBI
[2019-11-10T14:15:00.675] [INFO] shiny-server - Error getting worker: Error: The application exited during initialization.
Error in .jfindClass(as.character(driverClass)[1]) : 
  java.lang.ClassNotFoundException
Calls: runApp ... 
```

With `docker exec -it DOCKER_ID /bin/bash` I figured out, that the inbuilt and used `User shiny` has no rights on `/tmp/RtmpsAsij0/downloaded_packages`. 

1. Therefore I created the path: `RUN mkdir -p /tmp/RtmpsAsij0`
2. and made `User shiny` the owner of the path: `RUN chown shiny:shiny /tmp/RtmpsAsij0/`

Now hitting the localhost, no download happens! The app starts right away. 

So the question to think might be, whether to choose a path which is _visible by default_ to the shiny user.

Thanks again for your help!

**Comment by daroczig** [comment]
Hm, I'd be happy with the outcome, but that `/tmp/RtmpsAsij0` really worries me ... It's a temp dir that will change the next time your rebuild the Docker image I fear.

So we should track down how did the package installation and the `jar` ended up being there ... it might be a problem in where we download the `jar` (eg the new mechanism of R installing packages in temp dirs and then copying to the final destination) or something else.

So please reopen if it's a bug in `AWR.Athena` , eg if you are just doing a simple `install.packages`, then can you please check the location of the `jar` file afterwards? It should not be in `/tmp`... but something like:

```
> system.file('java/AthenaJDBC41_2.0.7.jar', package = 'AWR.Athena')
[1] "/usr/local/lib/R/site-library/AWR.Athena/java/AthenaJDBC41_2.0.7.jar"
```

**Comment by Zirkonium88** [comment]
Hey, just tried a `RUN chown shiny:shiny /tmp/` to avoid problem with regard to changing temporary paths - this is working as well. Additionally, the `jar` was in place.

```
shiny@aa0848417c31:/usr/local/lib/R/site-library/AWR.Athena/java$ ls
AthenaJDBC41_2.0.7.jar  log4j.properties
```

Also running the Docker Container as `root` solved the problem without changing permissions to `/tmp`.

So actually, the problem is caused by the permissions of `User shiny` ... which can be worked around by `RUN chown shiny:shiny /tmp/`.

**Comment by nfultz** [comment]
@daroczig do you think this is related to the changes around staged installation? I'm just speculating, but it seems like maybe the staged install is triggering a download, but the jar isn't getting copied over to final location?
