### ISSUE TITLE
CRAN removal

### ISSUE THREAD

**Issue by MattCowgill** [nfultz/AWR.Athena#25]
Hi, 
I note that the package was [removed from CRAN](https://cran.r-project.org/web/packages/AWR.Athena/index.html): 

```
Archived on 2023-04-13 at the request of the maintainer.
```

Is there a reason for this? If there's some fix required to keep it on CRAN, are you open to reviewing PR(s) that would address the issue(s)? 

Thank you

**Comment by nfultz** [comment]
I'm not going to support CRAN anymore so I had them remove it.

**Comment by MattCowgill** [comment]
OK, understood, thanks for the response @nfultz. Can I ask why you've decided not to support CRAN anymore? (As a package maintainer myself, I am sympathetic)

**Comment by nfultz** [comment]
You can email me at nfultz@gmail.com if you like.
