### ISSUE TITLE
Dealing with fetchSize internally

### ISSUE THREAD

**Issue by tonytonov** [nfultz/AWR.Athena#7]
It's probably a good idea to include the fix proposed at https://stackoverflow.com/questions/44379318/the-requested-fetchsize-is-more-than-the-allowed-value-in-athena-with-jdbc-dri to deal with "The requested fetchSize is more than the allowed value in Athena." issue. 

The solution itself is quite trivial, however incorporating it into the package is a bit trickier, since one needs to reexport the appropriate S4 method. I have a working solution at hand, so let me know if you'd like a PR.

**Comment by daroczig** [comment]
I just bumped into this issue -- can you please check if #8 solves this problem?

**Comment by nfultz** [comment]
I've posted an alternative fix in #9 taking the S4 route.

**Comment by nfultz** [comment]
Fixed, new version should be going to cran this week.

**Comment by tonytonov** [comment]
Thanks!
